spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin RETAIN_FIRST
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Content-Type
              - Authorization
              - Accept
              - Origin
            allowCredentials: true
      routes:
        - id: r1
          uri: http://localhost:8081/
          predicates:
            - Path=/auth/**
        - id: r2
          uri: http://localhost:8082/
          predicates:
            - Path=/offer/admin/**
          filters:
            - AuthenticationFilter
        - id: r2-user
          uri: http://localhost:8082/
          predicates:
            - Path=/offer/user/**
          filters:
            - AuthenticationFilter
        - id: r2-visitor
          uri: http://localhost:8082/
          predicates:
            - Path=/offer/visitor/**
        - id: r3
          uri: http://localhost:8083/
          predicates:
            - Path=/superadmin/**
          filters:
            - AuthenticationFilter

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
