eureka:
  client:
    service-url:
      defaultZone: http://localhost:9093/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: offres_all
          uri: lb://offres
          predicates:
            - Path=/api/v1/offres/all
        - id: offres_add
          uri: lb://offres
          predicates:
            - Path=/api/v1/offres/addoffre
            - Method=POST
        - id: offres_delete
          uri: lb://offres
          predicates:
            - Path=/api/v1/offres/deleteoffre/**
            - Method=DELETE
        - id: offres_update
          uri: lb://offres
          predicates:
            - Path=/api/v1/offres/updateoffre
            - Method=PUT
        - id: discovery
          uri: lb://discovery
          predicates:
            - Path=/discovery/**
          filters:
            - RewritePath=/discovery/(?<path>.*), /$\{path}
        - id: microservice-utilisateur
          uri: lb://microservice-utilisateur
          predicates:
            - Path=/utilisateur/**
          filters:
            - RewritePath=/utilisateur/(?<path>.*), /$\{path}
