spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          uri: http://localhost:9093/eureka
          lower-case-service-id: true
      routes:
        - id: offres_all
          uri: lb://offres
          predicates:
            - Path=/api/v1/offres/all
        - id: offres_add
          uri: lb://offres
          predicates:
            - Path=/api/v1/offres/addoffre
            - Method=POST
        - id: offres_delete
          uri: lb://offres
          predicates:
            - Path=/api/v1/offres/deleteoffre/**
            - Method=DELETE
        - id: offres_update
          uri: lb://offres
          predicates:
            - Path=/api/v1/offres/updateoffre
            - Method=PUT
        - id: utilisateur_authenticate
          uri: lb://microservice-utilisateur
          predicates:
            - Path=/authenticate
            - Method=POST
        - id: utilisateur_signup
          uri: lb://microservice-utilisateur
          predicates:
            - Path=/sign-up
            - Method=POST
        - id: discovery
          uri: lb://discovery
          predicates:
            - Path=/discovery/**
          filters:
            - RewritePath=/discovery/(?<path>.*), /$\{path}
