spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: offres_all
          uri: lb://offres
          predicates:
            - Path=/api/v1/offres/all
        - id: offres_add
          uri: lb://offres
          predicates:
            - Path=/api/v1/offres/addoffre
            - Method=POST
        - id: offres_delete
          uri: lb://offres
          predicates:
            - Path=/api/v1/offres/deleteoffre/**
            - Method=DELETE
        - id: offres_update
          uri: lb://offres
          predicates:
            - Path=/api/v1/offres/updateoffre
            - Method=PUT
        - id: user_all
          uri: lb://microservice-utilisateur
          predicates:
            - Path=/all
        - id: user_add
          uri: lb://microservice-utilisateur
          predicates:
            - Path=/add
            - Method=POST
        - id: user_add_role
          uri: lb://microservice-utilisateur
          predicates:
            - Path=/addRole/{id}
            - Method=POST
        - id: user_find_by_id
          uri: lb://microservice-utilisateur
          predicates:
            - Path=/findUserById/{id}
        - id: user_all_roles
          uri: lb://microservice-utilisateur
          predicates:
            - Path=/allRoles
        - id: user_find_role_by_id
          uri: lb://microservice-utilisateur
          predicates:
            - Path=/findRoleById/{id}
        - id: user_delete_by_id
          uri: lb://microservice-utilisateur
          predicates:
            - Path=/deleteUserById/{id}
            - Method=DELETE
        - id: user_remove_role
          uri: lb://microservice-utilisateur
          predicates:
            - Path=/removeRoleFromUer/{id}
            - Method=POST
        - id: user_register
          uri: lb://microservice-utilisateur
          predicates:
            - Path=/register
            - Method=POST
        - id: user_verify
          uri: lb://microservice-utilisateur
          predicates:
            - Path=/verify
            - Method=POST
        - id: discovery
          uri: lb://discovery
          predicates:
            - Path=/discovery/**
          filters:
            - RewritePath=/discovery/(?<path>.*), /$\{path}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9093/eureka/
    fetch-registry: true
    register-with-eureka: true
